<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[验证在登录界面，输入错误的手机号和密码，点击登录按钮后，无法正常登录成功，且对应提示信息显示正确]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="78379" started-at="2018-12-04T04:53:25Z" finished-at="2018-12-04T04:54:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="78379" started-at="2018-12-04T04:53:25Z" finished-at="2018-12-04T04:54:44Z">
      <class name="TestCases.WeChatLogin">
        <test-method status="PASS" signature="stup()[pri:0, instance:TestCases.WeChatLogin@34cd072c]" name="stup" is-config="true" duration-ms="50769" started-at="2018-12-04T12:53:25Z" finished-at="2018-12-04T12:54:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stup -->
        <test-method status="FAIL" signature="case1()[pri:0, instance:TestCases.WeChatLogin@34cd072c]" name="case1" duration-ms="6778" started-at="2018-12-04T12:54:16Z" finished-at="2018-12-04T12:54:23Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at AutomationTestSystem.Service.RunUnitService.runCase(RunUnitService.java:85)
	at TestCases.WeChatLogin.case1(WeChatLogin.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.AssertionError: 进入登录界面失败(实际结果和预期结果不一致)  Actual 【手机号登录】  but found 【手机号登录1】
	at org.testng.Assert.fail(Assert.java:94)
	at AutomationTestSystem.Handler.CheckActionHandler.checkEqualsAndroid(CheckActionHandler.java:153)
	at AutomationTestSystem.Handler.CheckActionHandler.androidCheck(CheckActionHandler.java:49)
	... 30 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case1 -->
        <test-method status="PASS" signature="case2()[pri:0, instance:TestCases.WeChatLogin@34cd072c]" name="case2" duration-ms="19501" started-at="2018-12-04T12:54:23Z" finished-at="2018-12-04T12:54:42Z">
          <reporter-output>
            <line>
              <![CDATA[验证在登录界面，输入错误的手机号和密码，点击登录按钮后，无法正常登录成功，且对应提示信息显示正确]]>
            </line>
          </reporter-output>
        </test-method> <!-- case2 -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:TestCases.WeChatLogin@34cd072c]" name="TearDown" is-config="true" duration-ms="1299" started-at="2018-12-04T12:54:42Z" finished-at="2018-12-04T12:54:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- TestCases.WeChatLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
