<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="P2P_PPM模式下-用户购买A系列手机"
           tests="54"
           failures="54"
           errors="0"
           skipped="0"
           time="61.192">
  <properties />
            <testcase name="case_45" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_45(P2P_TBJ_Mobile_SeriesB.java:306)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_45(P2P_TBJ_Mobile_SeriesB.java:306)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_27" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:50)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_27(P2P_TBJ_Mobile_SeriesB.java:198)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_20" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_20(P2P_TBJ_Mobile_SeriesB.java:156)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_20(P2P_TBJ_Mobile_SeriesB.java:156)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_34" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_34(P2P_TBJ_Mobile_SeriesB.java:240)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_34(P2P_TBJ_Mobile_SeriesB.java:240)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case1" time="0.007" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case1(P2P_TBJ_Mobile_SeriesB.java:42)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.handler.SlideAction_Handler.commonSlide(SlideAction_Handler.java:185)
  com.dafycredit.giveu.test.handler.SlideAction_Handler.slideLeft(SlideAction_Handler.java:40)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case1(P2P_TBJ_Mobile_SeriesB.java:42)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_16" time="0.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_16(P2P_TBJ_Mobile_SeriesB.java:132)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_16(P2P_TBJ_Mobile_SeriesB.java:132)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_14" time="0.072" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_14(P2P_TBJ_Mobile_SeriesB.java:120)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.handler.DBAction_Handler.dbQuery(DBAction_Handler.java:54)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_14(P2P_TBJ_Mobile_SeriesB.java:120)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_50" time="60.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_50(P2P_TBJ_Mobile_SeriesB.java:336)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.handler.SlideAction_Handler.commonSlide(SlideAction_Handler.java:185)
  com.dafycredit.giveu.test.handler.SlideAction_Handler.slideDown(SlideAction_Handler.java:92)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_50(P2P_TBJ_Mobile_SeriesB.java:336)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_33" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_33(P2P_TBJ_Mobile_SeriesB.java:234)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_33(P2P_TBJ_Mobile_SeriesB.java:234)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_41" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_41(P2P_TBJ_Mobile_SeriesB.java:282)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.handler.SlideAction_Handler.commonSlide(SlideAction_Handler.java:210)
  com.dafycredit.giveu.test.handler.SlideAction_Handler.slide(SlideAction_Handler.java:107)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_41(P2P_TBJ_Mobile_SeriesB.java:282)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_26" time="0.004" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_26(P2P_TBJ_Mobile_SeriesB.java:192)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_26(P2P_TBJ_Mobile_SeriesB.java:192)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_36" time="0.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_36(P2P_TBJ_Mobile_SeriesB.java:252)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_36(P2P_TBJ_Mobile_SeriesB.java:252)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_43" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_43(P2P_TBJ_Mobile_SeriesB.java:294)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.handler.SlideAction_Handler.commonSlide(SlideAction_Handler.java:185)
  com.dafycredit.giveu.test.handler.SlideAction_Handler.slideUp(SlideAction_Handler.java:74)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_43(P2P_TBJ_Mobile_SeriesB.java:294)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_28" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_28(P2P_TBJ_Mobile_SeriesB.java:204)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_28(P2P_TBJ_Mobile_SeriesB.java:204)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_32" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_32(P2P_TBJ_Mobile_SeriesB.java:228)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_32(P2P_TBJ_Mobile_SeriesB.java:228)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_46" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:50)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_46(P2P_TBJ_Mobile_SeriesB.java:312)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_15" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_15(P2P_TBJ_Mobile_SeriesB.java:126)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_15(P2P_TBJ_Mobile_SeriesB.java:126)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_18" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_18(P2P_TBJ_Mobile_SeriesB.java:144)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_18(P2P_TBJ_Mobile_SeriesB.java:144)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_21" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_21(P2P_TBJ_Mobile_SeriesB.java:162)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_38" time="0.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_38(P2P_TBJ_Mobile_SeriesB.java:264)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_38(P2P_TBJ_Mobile_SeriesB.java:264)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case7" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case7(P2P_TBJ_Mobile_SeriesB.java:78)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_13" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:50)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_13(P2P_TBJ_Mobile_SeriesB.java:114)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_29" time="0.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_29(P2P_TBJ_Mobile_SeriesB.java:210)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_29(P2P_TBJ_Mobile_SeriesB.java:210)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_30" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$2.run(Step_Action.java:40)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_30(P2P_TBJ_Mobile_SeriesB.java:216)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_17" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_17(P2P_TBJ_Mobile_SeriesB.java:138)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_17(P2P_TBJ_Mobile_SeriesB.java:138)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case5" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case5(P2P_TBJ_Mobile_SeriesB.java:66)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case3" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case3(P2P_TBJ_Mobile_SeriesB.java:54)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case3(P2P_TBJ_Mobile_SeriesB.java:54)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_10" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_10(P2P_TBJ_Mobile_SeriesB.java:96)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_10(P2P_TBJ_Mobile_SeriesB.java:96)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case4" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:50)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case4(P2P_TBJ_Mobile_SeriesB.java:60)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="Precondition" time="1.055" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.Precondition(P2P_TBJ_Mobile_SeriesB.java:30)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.handler.DBAction_Handler.dbUpdate(DBAction_Handler.java:42)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.Precondition(P2P_TBJ_Mobile_SeriesB.java:30)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_19" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_19(P2P_TBJ_Mobile_SeriesB.java:150)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_19(P2P_TBJ_Mobile_SeriesB.java:150)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case2" time="0.006" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case2(P2P_TBJ_Mobile_SeriesB.java:48)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case2(P2P_TBJ_Mobile_SeriesB.java:48)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_49" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_49(P2P_TBJ_Mobile_SeriesB.java:330)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_49(P2P_TBJ_Mobile_SeriesB.java:330)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_51" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.base.Step_Action$8.run(Step_Action.java:100)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_51(P2P_TBJ_Mobile_SeriesB.java:342)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_44" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.base.Step_Action$8.run(Step_Action.java:100)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_44(P2P_TBJ_Mobile_SeriesB.java:300)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_52" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_52(P2P_TBJ_Mobile_SeriesB.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.parseStringHasEls(Appium_Util.java:119)
  com.dafycredit.giveu.test.handler.DBAction_Handler.dbProcedure(DBAction_Handler.java:58)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_52(P2P_TBJ_Mobile_SeriesB.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_22" time="0.012" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_22(P2P_TBJ_Mobile_SeriesB.java:168)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_47" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_47(P2P_TBJ_Mobile_SeriesB.java:318)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_47(P2P_TBJ_Mobile_SeriesB.java:318)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_31" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_31(P2P_TBJ_Mobile_SeriesB.java:222)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_31(P2P_TBJ_Mobile_SeriesB.java:222)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_23" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_23(P2P_TBJ_Mobile_SeriesB.java:174)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_23(P2P_TBJ_Mobile_SeriesB.java:174)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_53" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_53(P2P_TBJ_Mobile_SeriesB.java:354)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.parseStringHasEls(Appium_Util.java:119)
  com.dafycredit.giveu.test.handler.DBAction_Handler.dbQuery(DBAction_Handler.java:48)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_53(P2P_TBJ_Mobile_SeriesB.java:354)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_35" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.base.Step_Action$8.run(Step_Action.java:100)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_35(P2P_TBJ_Mobile_SeriesB.java:246)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_37" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.base.Step_Action$8.run(Step_Action.java:100)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_37(P2P_TBJ_Mobile_SeriesB.java:258)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case9" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case9(P2P_TBJ_Mobile_SeriesB.java:90)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_25" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_25(P2P_TBJ_Mobile_SeriesB.java:186)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_25(P2P_TBJ_Mobile_SeriesB.java:186)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_24" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_24(P2P_TBJ_Mobile_SeriesB.java:180)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_24(P2P_TBJ_Mobile_SeriesB.java:180)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_12" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_12(P2P_TBJ_Mobile_SeriesB.java:108)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_12(P2P_TBJ_Mobile_SeriesB.java:108)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_40" time="0.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_40(P2P_TBJ_Mobile_SeriesB.java:276)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_40(P2P_TBJ_Mobile_SeriesB.java:276)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_42" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_42(P2P_TBJ_Mobile_SeriesB.java:288)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_42(P2P_TBJ_Mobile_SeriesB.java:288)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_39" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_39(P2P_TBJ_Mobile_SeriesB.java:270)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_39(P2P_TBJ_Mobile_SeriesB.java:270)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case6" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:50)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case6(P2P_TBJ_Mobile_SeriesB.java:72)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case8" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
  TestCases.P2P_TBJ_Mobile_SeriesB.case8(P2P_TBJ_Mobile_SeriesB.java:84)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_11" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_11(P2P_TBJ_Mobile_SeriesB.java:102)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
  com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_11(P2P_TBJ_Mobile_SeriesB.java:102)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="case_48" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
                <failure type="java.lang.reflect.InvocationTargetException"
                  message="(null)"
              >
<![CDATA[java.lang.reflect.InvocationTargetException
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_48(P2P_TBJ_Mobile_SeriesB.java:324)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
  com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
  com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
  TestCases.P2P_TBJ_Mobile_SeriesB.case_48(P2P_TBJ_Mobile_SeriesB.java:324)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
